### ISSUE TITLE
Export ignoring label rotation

### ISSUE THREAD

**Issue by walteralvarado** [imclem/Highcharts-export-module-asp.net#26] opened 2014-10-08 16:44 UTC
If I set label rotation in the xAxis, the export ignores this setting. Say I set in my chart options

xAxis: { labels: { rotation: 90 } }

Then the chart displays the X labels vertically, but the export show them horizontally.

**Comment by imclem** [comment] 2014-12-23 16:09
Probably linked to SVG.dll can you try with latest version on master (I've just merged the one with the new SVG.dll)

**Comment by imclem** [comment] 2014-12-23 16:13
If the issue is still present try to ask there (https://github.com/vvvv/SVG)

**Closed as completed by imclem** 2014-12-23 16:13 UTC
